server:
  port: 8761
  
spring:
  application:
    name: store-discovery

management:
  endpoints:
    web:
      base-path: /discovery/actuator
      exposure:
        include: [ '*' ]

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
